server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location /backgammon/static/ { alias /srv/game-static/; }
    location /static/ { alias /srv/tournaments-static/; }
    location /media/ { alias /srv/media/; }
    location /tournaments-static/ { alias /srv/tournaments-static/; }
    location /tournaments-media/ { alias /srv/media/; }
    location / {
        rewrite ^/(backgammon|tournaments|tournaments-admin)/(.*)$ /$2 break;
        try_files $uri $uri/ /index.html;
    }
}
