# Generated by Django 4.2.7 on 2026-07-27 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('match_type', models.CharField(default='online', max_length=10)),
                ('target_points', models.IntegerField(default=7)),
                ('white_score', models.IntegerField(default=0)),
                ('black_score', models.IntegerField(default=0)),
                ('winner', models.CharField(blank=True, max_length=5, null=True)),
                ('games', models.JSONField(default=list)),
                ('black_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
