# Generated by Django 4.2.7 on 2026-08-01 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_players(apps, schema_editor):
    """Create Player + RoomPlayer rows from the old User FKs on GameRoom,
    and repoint Match.white_player/black_player from User to Player."""
    GameRoom = apps.get_model('game', 'GameRoom')
    RoomPlayer = apps.get_model('game', 'RoomPlayer')
    Match = apps.get_model('game', 'Match')
    Player = apps.get_model('game', 'Player')

    players_by_user = {}

    def get_player(user_id):
        if user_id is None:
            return None
        if user_id not in players_by_user:
            players_by_user[user_id], _ = Player.objects.get_or_create(user_id=user_id)
        return players_by_user[user_id]

    for room in GameRoom.objects.all():
        white_user_id = room.white_player_id
        black_user_id = room.black_player_id
        white = get_player(white_user_id)
        black = get_player(black_user_id)
        if white:
            RoomPlayer.objects.get_or_create(room=room, player=white, color='white')
        if black:
            RoomPlayer.objects.get_or_create(room=room, player=black, color='black')

    for match in Match.objects.all():
        white = get_player(match.white_player_id)
        black = get_player(match.black_player_id)
        if white:
            match.white_player_id = white.id
        if black:
            match.black_player_id = black.id
        match.save(update_fields=['white_player', 'black_player'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_alter_gameroom_code_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('rating', models.IntegerField(default=1000)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('win_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gameroom',
            name='last_sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='game.gameroom'),
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to='game.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gameroom')),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(default=0)),
                ('event_type', models.CharField(choices=[('roll', 'Roll'), ('move', 'Move'), ('undo', 'Undo'), ('end_turn', 'End turn'), ('double', 'Double'), ('double_response', 'Double response'), ('resign', 'Resign')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='game.roomplayer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.gameroom')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.RunPython(backfill_players),
        migrations.RemoveField(
            model_name='gameroom',
            name='black_player',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='white_player',
        ),
        migrations.AlterField(
            model_name='match',
            name='black_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins_black', to='game.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='white_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins_white', to='game.player'),
        ),
        migrations.AddConstraint(
            model_name='roomplayer',
            constraint=models.UniqueConstraint(fields=('room', 'color'), name='unique_room_color'),
        ),
        migrations.AddConstraint(
            model_name='roomplayer',
            constraint=models.UniqueConstraint(fields=('room', 'player'), name='unique_room_player'),
        ),
    ]
