# Generated by Django 4.2.7 on 2026-08-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_remove_gameroom_black_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='time_control',
            field=models.CharField(default='2+12', max_length=20),
        ),
    ]
