# Generated by Django 4.2.7 on 2026-08-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gameroom_time_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='time_control',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
