# Generated by Django 4.2.7 on 2026-08-10 01:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_add_task_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='clock_remaining',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='doubles_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='doubles_offered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='end_reason',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='final_cube',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='first_player',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='opening_roll',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='event_type',
            field=models.CharField(choices=[('roll', 'Roll'), ('move', 'Move'), ('undo', 'Undo'), ('end_turn', 'End turn'), ('double', 'Double'), ('double_response', 'Double response'), ('resign', 'Resign'), ('next_game', 'Next game')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
