# Generated by Django 4.2.7 on 2026-08-29 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0007_match_clock_remaining_match_doubles_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.UUIDField(unique=True)),
                ('issuer', models.CharField(max_length=32)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=32)),
                ('tournament_id', models.IntegerField()),
                ('fixture_id', models.IntegerField()),
                ('seat_p1_color', models.CharField(default='white', max_length=5)),
                ('result_status', models.CharField(default='pending', max_length=16)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_link', to='game.gameroom')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=32)),
                ('external_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_identities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tournamentlink',
            constraint=models.UniqueConstraint(fields=('issuer', 'fixture_id'), name='unique_issuer_fixture'),
        ),
        migrations.AddConstraint(
            model_name='linkedidentity',
            constraint=models.UniqueConstraint(fields=('issuer', 'external_id'), name='unique_issuer_external_id'),
        ),
    ]
