# Generated by Django 4.2.7 on 2026-08-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_tournament_tournamentsignup_bracketmatch_and_more'),
        ('game', '0009_tournamentlink_result_body'),
    ]

    operations = [
    ]
