# Generated by Django 4.2.7 on 2026-09-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_aisession'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisession',
            name='purchase_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
