import styles from "../GameScreen/GameScreen.module.css";
import type { BoardTheme } from "./boardThemes";

const classicClasses = "[--lux-material-texture:none] [--lux-photo-texture-opacity:0] [--lux-frame-texture-opacity:0] [--lux-point-texture-opacity:0] [--lux-field-sheen:none] [--lux-row-bg:none] [--lux-point-light-sheen:transparent] [--lux-point-dark-sheen:transparent] [--lux-point-edge:transparent] [--lux-point-edge-soft:transparent] [--lux-point-fiber:transparent] [--lux-checker-light-hi:#ffffff] [--lux-checker-light-mid:#fffdf5] [--lux-checker-light-low:#e6e0cf] [--lux-checker-light-deep:#aaa390] [--lux-checker-light-border:#d1cbbd] [--lux-checker-dark-hi:#343434] [--lux-checker-dark-mid:#111111] [--lux-checker-dark-low:#080808] [--lux-checker-dark-deep:#000000] [--lux-checker-dark-border:#050505] [--lux-die-dark-hi:#303030] [--lux-die-dark-low:#101010] [--lux-die-pip-light:#ffffff] [--lux-die-pip-dark:#111111] [--lux-panel-bg:#101314] [--ui-accent:#d6ae63] [--ui-accent-hover:#e8c680] [--ui-accent-soft:#d6ae633d] [--ui-accent-faint:#d6ae6324] [--ui-accent-border:#d6ae6380] [--ui-accent-glow:#d6ae6340] [--ui-on-accent:#17130c] [--ui-secondary-bg:#242424] [--ui-secondary-border:#d6ae6366] [--ui-menu-bg:#101314] [--ui-bar-overlay:none] [--ui-cube-bg:#161616] [--lux-case-glow-top:#ffffff1a] [--lux-case-glow-side:#ffffff0d] [--lux-case-shadow-bottom:#00000040] [--lux-inner-border:#00000033] [--lux-case-border:#8d6a41] [--lux-rail-border:#8d6a41] [--lux-rivet:#b58c4e] [--lux-rivet-soft:#b58c4e33]";

export const boardThemeClasses: Record<BoardTheme, string> = {
  redGreen: `${styles.defaultTheme} ${styles.themeRedGreen}`,
  blueIvory: `${styles.defaultTheme} ${styles.themeBlueIvory}`,
  ivoryGold: `${styles.defaultTheme} ${styles.themeIvoryGold}`,
  classicBrown: `${classicClasses} [&_[data-testid=board-inner-frame]]:[background:var(--lux-rail-bg)] [--lux-case-bg:#382016] [--lux-rail-bg:#382016] [--lux-board-area-bg:#382016] [--lux-field-bg:#76513a] [--lux-bar-bg:#382016] [--lux-bearoff-bg:#382016] [--lux-center-belt:#76513a] [--lux-point-light-a:#bc844b] [--lux-point-light-b:#bc844b] [--lux-point-dark-a:#4b3023] [--lux-point-dark-b:#4b3023]`,
  classicLight: `${classicClasses} [&_[data-testid=board-inner-frame]]:[background:var(--lux-rail-bg)] [--lux-case-bg:#d8c9a9] [--lux-rail-bg:#d8c9a9] [--lux-board-area-bg:#d8c9a9] [--lux-field-bg:#ede8d7] [--lux-bar-bg:#d8c9a9] [--lux-bearoff-bg:#d8c9a9] [--lux-center-belt:#ede8d7] [--lux-point-light-a:#b82e38] [--lux-point-light-b:#b82e38] [--lux-point-dark-a:#191c20] [--lux-point-dark-b:#191c20]`,
};
